services:
  redis:
    image: redis:7
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379/tcp"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 15

  live777:
    image: ghcr.io/binbat/live777-server:0.7.3
    container_name: live777
    hostname: live777
    ports:
      - "7777:7777/tcp"

  woom:
    build: .
    container_name: woom
    depends_on:
      redis:
        condition: service_healthy
      live777:
        condition: service_started
    environment:
      REDIS_URL: redis://redis:6379/0
      LIVE777_URL: http://live777:7777
    ports:
      - "4000:4000/tcp"

networks:
  default:
    name: woom
